"""
Report Generator
Takes health analysis data and creates formatted text reports.
"""

from datetime import datetime, timezone


class ReportGenerator:
    """Generates human-readable reports from health analysis data."""

    @staticmethod
    def generate_text_report(channel_name: str, health_data: dict) -> str:
        """
        Generate a plain text health report.

        Args:
            channel_name: Channel name
            health_data: Dict from HealthAnalyzer

        Returns:
            Formatted report string
        """
        status_emoji = {
            "green": "🟢",
            "yellow": "🟡",
            "red": "🔴",
        }

        score = health_data.get("score", 0)
        status = health_data.get("status", "yellow")
        emoji = status_emoji.get(status, "⚪")

        lines = [
            f"{emoji} *#{channel_name}* — Health Score: *{score}/100*",
            "",
            health_data.get("summary", "No summary available."),
        ]

        # Blockers
        blockers = health_data.get("blockers", [])
        if blockers:
            lines.append("")
            lines.append("🚧 *Blockers:*")
            for b in blockers:
                severity = b.get("severity", "medium").upper()
                lines.append(f"  • [{severity}] {b.get('description', 'Unknown blocker')}")

        # Risks
        risks = health_data.get("risks", [])
        if risks:
            lines.append("")
            lines.append("⚠️ *Risks:*")
            for r in risks:
                lines.append(f"  • {r.get('description', 'Unknown risk')}")

        # Highlights
        highlights = health_data.get("highlights", [])
        if highlights:
            lines.append("")
            lines.append("✨ *Highlights:*")
            for h in highlights:
                lines.append(f"  • {h}")

        # Recommendations
        recommendations = health_data.get("recommendations", [])
        if recommendations:
            lines.append("")
            lines.append("💡 *Recommendations:*")
            for r in recommendations:
                lines.append(f"  • {r}")

        # Footer
        lines.append("")
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines.append(f"_Report generated by SlackScope at {now}_")

        return "\n".join(lines)

    @staticmethod
    def generate_multi_channel_summary(reports: list[dict]) -> str:
        """
        Generate a summary across multiple channels.

        Args:
            reports: List of dicts with 'channel_name' and 'health_data'

        Returns:
            Combined report string
        """
        status_emoji = {"green": "🟢", "yellow": "🟡", "red": "🔴"}

        lines = [
            "📊 *SlackScope Daily Health Report*",
            f"_{datetime.now(timezone.utc).strftime('%A, %B %d, %Y')}_",
            "",
            "─" * 30,
        ]

        # Sort by score (worst first to draw attention)
        sorted_reports = sorted(reports, key=lambda r: r["health_data"].get("score", 0))

        for report in sorted_reports:
            name = report["channel_name"]
            data = report["health_data"]
            score = data.get("score", 0)
            status = data.get("status", "yellow")
            emoji = status_emoji.get(status, "⚪")
            summary = data.get("summary", "")

            lines.append(f"{emoji} *#{name}* — {score}/100")
            lines.append(f"   {summary}")

            blockers = data.get("blockers", [])
            if blockers:
                lines.append(f"   🚧 {len(blockers)} blocker(s)")

            lines.append("")

        # Overall stats
        scores = [r["health_data"].get("score", 0) for r in reports]
        avg_score = sum(scores) // len(scores) if scores else 0
        total_blockers = sum(len(r["health_data"].get("blockers", [])) for r in reports)

        lines.append("─" * 30)
        lines.append(f"📈 Average Health: *{avg_score}/100* | 🚧 Total Blockers: *{total_blockers}*")
        lines.append("")
        lines.append("_Use `/slackscope health #channel` for detailed reports_")

        return "\n".join(lines)
